# Generated by Django 4.2.4 on 2023-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creador', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('radio', models.DecimalField(decimal_places=0, max_digits=3)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
    ]
